services:
  - type: web
    name: Stock-management
    runtime: php
    buildCommand: composer install --optimize-autoloader --no-dev && php artisan optimize
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    env: php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
    database:
      name: mysql 