services:
  - type: web
    name: laravel-sqlite-app 
    runtime: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      touch storage/database.sqlite
      php artisan migrate --force
      php artisan optimize
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true 
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/storage/database.sqlite
    disk:
      name: storage
      mountPath: /var/www/storage
      sizeGB: 1  # Stockage persistant pour SQLite